Do not declare `Main-Class`es
Replace
```
Error: Unable to initialize main class com.sun.enterprise.admin.cli.AdminMain
Caused by: java.lang.NoClassDefFoundError: org/glassfish/api/admin/CommandValidationException
```

with
```
no main manifest attribute, in admin-cli.jar
```