Give a clearer error message if datasource is not defined.
First exception gives a good error message, but then an extension is used as a fallback, and then it gives a very confusing message, like:

ConnectorRuntimeException: Invalid resource: org.glassfish.resourcebase.resources.api.ResourceInfo@f7d823e4[jndiName=java:app/jdbc/CargoTrackerDatabase__pm, applicationName=Eclipse_Cargo_Tracker, moduleName=null]

It refers to JNDI name with the cryptic __pm suffix, and says "Invalid resource", instead of syaing that the datasource could not be looked up

This improvement will print into about the first exception, followed by the second exception as suppressed.